sudo: false
language: node_js
node_js:
- "stable"
addons:
  chrome: stable
services:
- postgresql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - "rake db:migrate"
script:
- npm run test
- npm run coverage
after_success: npm run coverage
