sudo: false
language: node_js
node_js:
- "stable"
addons:
  chrome: stable
services:
- postgresql
before_script:
 - psql -c 'drop database if exists users;' -U postgres
 - psql -c 'create database users;' -U postgres
 - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
 - sequelize db:migrate
- sequelize db:seed:all
script:
- npm test
- npm run coverage
after_success: npm run coverage
